branch-defaults:
  default:
    environment: python-ardu
    group_suffix: null
global:
  application_name: flask-kimchi
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
